blank_issues_enabled: true
contact_links:
  - name: DSF Documentation
    url: https://dsf.dev/process-development/linter-tool/linter-tool.html
    about: Read the DSF Linter documentation.
  - name: Getting Help
    url: https://github.com/datasharingframework/dsf-linter/discussions
    about: For general questions about the DSF Linter, please use GitHub Discussions.
