package dev.dsf.utils.validator.plugin;

import dev.dsf.utils.validator.DsfValidatorImpl;
import dev.dsf.utils.validator.exception.MissingServiceRegistrationException;
import dev.dsf.utils.validator.exception.ResourceValidationException; // Import
import dev.dsf.utils.validator.logger.Logger;
import dev.dsf.utils.validator.plugin.logger.MavenMojoLogger;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugin.logging.Log;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.slf4j.LoggerFactory;


import java.io.File;
import java.io.IOException;

/**
 * <h2>DSF Validator Maven Plugin – Mojo: verify</h2>
 *
 * <p>
 * This Mojo executes the Digital Sample Framework (DSF) validation during the Maven lifecycle
 * (default phase: {@code verify}). It uses the centralized logic in {@link DsfValidatorImpl}
 * to perform a definition-driven validation of a DSF process plugin.
 * </p>
 *
 * <h3>Core Logic</h3>
 * <p>
 * The Mojo delegates the entire validation workflow to {@link DsfValidatorImpl#validate(java.nio.file.Path)},
 * which includes:
 * </p>
 * <ul>
 * <li>Building the project via Maven to ensure all dependencies are available.</li>
 * <li>Discovering and loading the project's {@code ProcessPluginDefinition}.</li>
 * <li>Validating all resources referenced in the definition (FHIR resources, BPMN processes, etc.).</li>
 * <li>Checking for unreferenced "leftover" files that may indicate configuration issues.</li>
 * <li>Verifying ServiceLoader registration for proper plugin discovery.</li>
 * <li>Generating a comprehensive, structured JSON validation report.</li>
 * </ul>
 * <p>
 * This Mojo's primary responsibility is to integrate the validation process into the Maven build
 * lifecycle and translate validation exceptions into appropriate Maven build failures
 * ({@link MojoFailureException} or {@link MojoExecutionException}).
 * </p>
 *
 * <h3>Exception Handling</h3>
 * <ul>
 * <li>{@link MissingServiceRegistrationException} – Handled based on {@code failOnMissingService} parameter</li>
 * <li>{@link ResourceValidationException} – Always causes build failure due to invalid resource syntax</li>
 * <li>{@link IllegalStateException} – Always causes build failure due to configuration errors</li>
 * <li>{@link IOException}/{@link InterruptedException} – Unexpected execution errors causing build failure</li>
 * </ul>
 *
 * <h3>Configuration Parameters</h3>
 * <ul>
 * <li><strong>-Ddsf.skip=true</strong> – Completely skips validator execution</li>
 * <li><strong>-Ddsf.failOnMissingService=false</strong> – Treats missing ServiceLoader registration as warning instead of error</li>
 * <li><strong>-Ddsf.report.dir=path</strong> – Custom directory for validation reports (handled by core validator)</li>
 * </ul>
 *
 * @author DSF Team
 * @version 2.0
 * @since 1.0
 */
@Mojo(
        name = "verify",
        defaultPhase = LifecyclePhase.VERIFY,
        requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME,
        threadSafe = true
)
public class ValidateMojo extends AbstractMojo
{
    private final org.slf4j.Logger log = LoggerFactory.getLogger(getClass());

    @Parameter(defaultValue = "${project.basedir}", readonly = true)
    private File baseDirectory;

    /**
     * The build directory is now read from the system property 'dsf.report.dir' by the core validator,
     * but is kept here for context. The report is generated by default under 'target/report/'.
     */
    @Parameter(defaultValue = "${project.build.directory}", readonly = true)
    private File buildDirectory;

    /**
     * Fail the build if ServiceLoader registration is missing.
     */
    @Parameter(property = "dsf.failOnMissingService", defaultValue = "true")
    private boolean failOnMissingService;

    /**
     * Allow skipping the plugin goal entirely.
     */
    @Parameter(property = "dsf.skip", defaultValue = "false")
    private boolean skip;

    /**
     * Executes the validation process by delegating to DsfValidatorImpl.
     */
    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (skip) {
            log.info("DSF validation is skipped (dsf.skip=true).");
            return;
        }

        // Der Adapter umschließt jetzt den SLF4J Logger
        Logger validatorLogger = new MavenMojoLogger(log);
        DsfValidatorImpl validator = new DsfValidatorImpl(validatorLogger);

        try {
            log.info("Starting DSF process plugin validation...");
            validator.validate(baseDirectory.toPath());
            log.info("DSF validation finished successfully.");
        } catch (MissingServiceRegistrationException e) {
            if (failOnMissingService) {
                log.error("Fatal: {}", e.getMessage());
                throw new MojoFailureException("Missing ServiceLoader registration for ProcessPluginDefinition. See reports for details.", e);
            } else {
                log.warn("A MissingServiceRegistrationException occurred, but 'failOnMissingService' is false. Build will continue.", e);
            }
        } catch (IllegalStateException e) {
            log.error("Fatal configuration error: {}", e.getMessage());
            throw new MojoFailureException("A fatal configuration error occurred during validation: " + e.getMessage(), e);
        } catch (ResourceValidationException e) {
            log.error("Fatal validation error: A resource file could not be parsed.");
            log.error("File: {}", e.getFilePath().toString());
            log.error("Reason: {}", e.getCause().getMessage());
            throw new MojoFailureException("A resource file contains a syntax error. See logs for details.", e);
        } catch (IOException | InterruptedException e) {
            log.error("An unexpected execution error occurred during validation.", e);
            throw new MojoExecutionException("An unexpected error occurred during validation.", e);
        }
    }
}