package dev.dsf.utils.validator;

public enum ValidationType {

    UNPARSABLE_FHIR_RESOURCE,

    UNPARSABLE_BPMN_FILE,

    // BPMN

    // bpmn common
    BPMN_PROCESS_ID_MISSING,

    BPMN_PROCESS_ID_INVALID,

    BPMN_PROCESS_ID_NO_ACTIVITY_DEFINITION_FOUND,

    BPMN_PROCESS_VERSION_TAG_MISSING,

    BPMN_PROCESS_VERSION_TAG_INVALID,

    BPMN_PROCESS_VERSION_TAG_NO_PLACEHOLDER, // warning

    // bpmn service task
    BPMN_SERVICE_TASK_IMPLEMENTATION_CLASS_EMPTY,

    BPMN_SERVICE_TASK_IMPLEMENTATION_CLASS_NOT_FOUND,

    // bpmn message send event
    BPMN_MESSAGE_SEND_EVENT_IMPLEMENTATION_CLASS_EMPTY,

    BPMN_MESSAGE_SEND_EVENT_IMPLEMENTATION_CLASS_NOT_FOUND,

    BPMN_MESSAGE_SEND_EVENT_PROFILE_EMPTY,

    BPMN_MESSAGE_SEND_EVENT_PROFILE_NOT_FOUND,

    BPMN_MESSAGE_SEND_EVENT_MESSAGE_NAME_EMPTY,

    BPMN_MESSAGE_SEND_EVENT_MESSAGE_NAME_NOT_MATCHING_PROFILE,

    BPMN_MESSAGE_SEND_EVENT_INSTANTIATES_CANONICAL_EMPTY,

    BPMN_MESSAGE_SEND_EVENT_INSTANTIATES_CANONICAL_NOT_MATCHING_PROFILE,

    BPMN_MESSAGE_SEND_EVENT_MESSAGE_NAME_NOT_PRESENT_IN_ACTIVITY_DEFINITION,

    // bpmn message send task
    BPMN_MESSAGE_SEND_TASK_IMPLEMENTATION_CLASS_EMPTY,

    BPMN_MESSAGE_SEND_TASK_IMPLEMENTATION_CLASS_NOT_FOUND,

    BPMN_MESSAGE_SEND_TASK_PROFILE_EMPTY,

    BPMN_MESSAGE_SEND_TASK_PROFILE_NOT_FOUND,

    BPMN_MESSAGE_SEND_TASK_MESSAGE_NAME_EMPTY,

    BPMN_MESSAGE_SEND_TASK_MESSAGE_NAME_NOT_MATCHING_PROFILE,

    BPMN_MESSAGE_SEND_TASK_INSTANTIATES_CANONICAL_EMPTY,

    BPMN_MESSAGE_SEND_TASK_INSTANTIATES_CANONICAL_NOT_MATCHING_PROFILE,

    // bpmn flow
    BPMN_MESSAGE_START_EVENT_NOT_FOUND,

    BPMN_MESSAGE_START_EVENT_MESSAGE_NAME_EMPTY,

    BPMN_MESSAGE_START_EVENT_MESSAGE_NAME_NOT_MATCHING_PROFILE, // -> Structure Definition present

    BPMN_MESSAGE_START_EVENT_MESSAGE_NAME_NOT_PRESENT_IN_ACTIVITY_DEFINITION,

    BPMN_SEQUENCE_FLOW_AMBIGUOUS,

    BPMN_FLOATING_ELEMENT, // bpmn element outside of message start event triggered flow

    // FHIR

    MISSING_ACTIVITY_DEFINITION_FOR_PROCESS,

    ACTIVITY_DEFINITION_VERSION_NO_PLACEHOLDER, // warning

    ACTIVITY_DEFINITION_DATE_NO_PLACEHOLDER, // warning


    ACTIVITY_DEFINITION_ENTRY_INVALID_REQUESTER,

    ACTIVITY_DEFINITION_ENTRY_INVALID_RECIPIENT,

    MISSING_STRUCTURE_DEFINITION_FOR_PROFILE,

    UNUSED_FHIR_RESOURCE,


    // PluginDefinition
    PLUGIN_DEFINITION_INVALID,

    PLUGIN_DEFINITION_BPMN_FILE_NOT_FOUND,

    PLUGIN_DEFINITION_FHIR_RESSOURCE_NOT_FOUND,

    PLUGIN_DEFINITION_BPMN_FILE_NOT_LISTED,

    PLUGIN_DEFINITION_FHIR_RESSOURCE_NOT_LISTED,

    // new addition @khalil BPMN
    BPMN_ERROR_BOUNDARY_EVENT_ERROR_CODE_EMPTY,
    BPMN_ERROR_BOUNDARY_EVENT_ERROR_CODE_VARIABLE_EMPTY,
    BPMN_ERROR_BOUNDARY_EVENT_ERROR_NAME_EMPTY,
    BPMN_ERROR_BOUNDARY_EVENT_NAME_EMPTY,
    BPMN_FIELD_INJECTION_NOT_STRING_LITERAL,
    BPMN_SERVICE_TASK_IMPLEMENTATION_CLASS_NOT_IMPLEMENTING_JAVA_DELEGATE,
    BPMN_SERVICE_TASK_NAME_EMPTY,
    BPMN_UNKNOWN_FIELD_INJECTION,
    BPMN_MESSAGE_INTERMEDIATE_THROW_EVENT_HAS_MESSAGE,
    BPMN_FIELD_INJECTION_INSTANTIATES_CANONICAL_EMPTY,
    BPMN_FIELD_INJECTION_INSTANTIATES_CANONICAL_NO_VERSION_PLACEHOLDER,
    BPMN_FIELD_INJECTION_PROFILE_EMPTY,
    BPMN_FIELD_INJECTION_PROFILE_NO_VERSION_PLACEHOLDER,
    BPMN_FIELD_INJECTION_MESSAGE_VALUE_EMPTY,
    BPMN_EVENT_NAME_EMPTY,
    BPMN_MESSAGE_SEND_EVENT_IMPLEMENTATION_CLASS_NOT_IMPLEMENTING_JAVA_DELEGATE,
    BPMN_START_EVENT_NOT_PART_OF_SUB_PROCESS,
    BPMN_END_EVENT_NOT_PART_OF_SUB_PROCESS,
    BPMN_SERVICE_TASK_IMPLEMENTATION_NOT_EXIST,
    BPMN_MESSAGE_INTERMEDIATE_CATCH_EVENT_NAME_EMPTY,
    BPMN_MESSAGE_BOUNDARY_EVENT_NAME_EMPTY,
    BPMN_FLOW_ELEMENT,

    // new addition FHIR
    INVALID_FHIR_URL,
    INVALID_FHIR_STATUS,
    MISSING_REQUIRED_FIELD,
    INVALID_FHIR_ACCESS_TAG,
    INVALID_FHIR_TAG_SYSTEM,
    INVALID_FHIR_ACCESS_TAG_CODE,
    UNKNOWN,
    FHIR_STATUS_IS_NOT_SET_AS_UNKNOWN,
    INVALID_FHIR_KIND,
    FHIR_KIND_NOT_SET_AS_TASK,
    SUCCESS,
    NO_EXTENSION_PROCESS_AUTHORIZATION_FOUND,
    MISSING_FHIR_ACCESS_TAG,
    MISSING_RECIPIENT_EXTENSION,
    MISSING_REQUESTER_EXTENSION
}
